//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNion_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_History
    {
        public int id { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_staff { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
